### ISSUE TITLE
Is there a follow-up development plan?

### ISSUE THREAD

**Issue by kingzcheung** [milvus-io/milvus-sdk-rust#1]
We need the rust version of sdk, and if it's not that fast, we'd like to implement it ourselves based on protobuf once.

**Comment by yah01** [comment]
> We need the rust version of sdk, and if it's not that fast, we'd like to implement it ourselves based on protobuf once.

For now, we are planning to start it on 1st July, most of things should be done before Sep.

**Comment by kingzcheung** [comment]
Thks 4 amazing work!

**Comment by codabrink** [comment]
Hey @yah01, have you taken a look at my work in https://github.com/codabrink/milvus-sdk-rust ?

**Comment by yah01** [comment]
> Hey @yah01, have you taken a look at my work in https://github.com/codabrink/milvus-sdk-rust ?

Sure, I replied to your email, guess you missed that...
