### ISSUE TITLE
Rust sdk is slower than go sdk in same collection

### ISSUE THREAD

**Issue by kingzcheung** [milvus-io/milvus-sdk-rust#27]
It has 77,536 entity count in the collection.

![image](https://user-images.githubusercontent.com/12839855/199935949-1a01cdaa-1ae7-4348-95a0-bb5737f2851e.png)

In go sdk:

![image](https://user-images.githubusercontent.com/12839855/199937111-6a6d607e-faf8-4c64-9d87-7df8edc1cf2e.png)

The average of the results is at 48ms:
```
❯ go run client/main.go
since time: 47.607644ms
[396 308 515 1928 1311]
[0.99999964 0.99999964 0.99999964 0.99999964 0.99999964]
[6993931090704601089 6993934159068663809 6993926946082131969 6993888636357971969 6993903639333048321]
(base) 
ibuddy in ibuddy-Super-Server in tris/vs-server on  master [?] via 🐹 v1.18.1 
❯ go run client/main.go
since time: 48.362906ms
[1311 695 388 2204 246]
[0.99999964 0.99999964 0.99999964 0.99999964 0.99999964]
[6993903639333048321 6993920792450961409 6993931340936777729 6993881812346998785 6993936299845619713]
(base) 
ibuddy in ibuddy-Super-Server in tris/vs-server on  master [?] via 🐹 v1.18.1 
❯ go run client/main.go
since time: 48.501344ms
[396 308 515 1928 1311]
[0.99999964 0.99999964 0.99999964 0.99999964 0.99999964]
[6993931090704601089 6993934159068663809 6993926946082131969 6993888636357971969 6993903639333048321]
```

Rust sdk:
![image](https://user-images.githubusercontent.com/12839855/199937664-59002417-9399-4f61-87b7-2301203dbb42.png)

It(**search time**) takes between 180-300ms.

![image](https://user-images.githubusercontent.com/12839855/199940086-314c2ad6-1463-4110-b83e-c4482c904d41.png)
![image](https://user-images.githubusercontent.com/12839855/199940140-75a6385e-6537-472a-adf8-0f5109262a1a.png)
![image](https://user-images.githubusercontent.com/12839855/199940196-a1f98721-4af9-478e-a5c7-c2ccc7f3b793.png)

**Comment by yah01** [comment]
@kingzcheung Could you provide the code of creating collection? This looks like the two SDK use different consistency level

**Comment by yah01** [comment]
The GO SDK uses `Bounded` consistency level by default, as the Rust SDK uses the collection's

**Comment by kingzcheung** [comment]
> The GO SDK uses consistency level by default, as the Rust SDK uses the collection's`Bounded`

I used `Bounded` in creating collection. 

![image](https://user-images.githubusercontent.com/12839855/200218126-e4924d21-d89f-48a5-b706-43e332e6ca29.png)

**Comment by kingzcheung** [comment]
I had keep the same level in rust sdk and go sdk, and it not solved.

**Comment by yah01** [comment]
The Milvus server has not implemented the new consistency design, we will change the Rust SDK to behave like Go SDK.
