### ISSUE TITLE
Example error: index doesn't exist

### ISSUE THREAD

**Issue by apepkuss** [milvus-io/milvus-sdk-rust#43]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I ran the example "examples/collections.rs", I got the error message: 

```bash
failed to run hello milvus: Server(UnexpectedError, "index doesn't exist, collectionID 440648455792968346")
```

Is this example outdated? 

In addition, when will the first stable version be released? Thanks a lot!

**Comment by yah01** [comment]
The example is outdated, now Milvus requires index created before loading the collection, will update it

**Comment by apepkuss** [comment]
Thanks. Would you have any plan for releasing the first stable version?

**Comment by apepkuss** [comment]
@yah01 Thanks for the review!
