### ISSUE TITLE
[Feature]: Crates.io package

### ISSUE THREAD

**Issue by diptanu** [milvus-io/milvus-sdk-rust#47]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Trying to use Milvus from a Rust service

### Describe the solution you'd like.

Is this package going to be available on Crates.io? Trying to use this from a Rust service.

**Comment by divanvisagie** [comment]
I see that the "milvus" crate is owned by @andreytkachenko [here](https://github.com/andreytkachenko/milvus-rs). The API looks surprisingly similar, is this project a fork of it? Perhaps we could get them in sync?

**Comment by xiaofan-luan** [comment]
> I see that the "milvus" crate is owned by @andreytkachenko [here](https://github.com/andreytkachenko/milvus-rs). The API looks surprisingly similar, is this project a fork of it? Perhaps we could get them in sync?

Yep I thought andrey is one of the contributor of milvus rust SDKs. 
Once the SDK finally went to public we should keep everything in sync.

**Comment by divanvisagie** [comment]
Ah, I see that now, sorry, just trying out this lib for the first time. I was just quite confused because the crate links back to his repo which is on 0.2.0 while the code here is 0.1.0.

**Comment by yah01** [comment]
The crate package has been published, you could use it with `cargo add milvus-sdk-rust`
