### ISSUE TITLE
[Feature]: Add collection alias api 

### ISSUE THREAD

**Issue by kingzcheung** [milvus-io/milvus-sdk-rust#51]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

The SDK does not implement the Alias API

### Describe the solution you'd like.

I will implement the following APIs:

1. CreateAlias
2. DropAlias
3. AlterAlias

**Comment by yah01** [comment]
Fixed with #52
