### ISSUE TITLE
[Bug]: [UnexpectedError] Assert \"field_meta.get_sizeof() == element.line_sizeof_\"

### ISSUE THREAD

**Issue by kingzcheung** [milvus-io/milvus-sdk-rust#59]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I often drop the collection and then recreate the collection. but it always gets some errors inexplicably( **I don't do anything else**).

When i delete the `volumes` dir then i reimport the data. It's work when searching.

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0):
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by yah01** [comment]
@kingzcheung What's the version of Milvus, and any log or error message?

**Comment by yah01** [comment]
hi @kingzcheung, I would close this as it should be a bug of old version Milvus and has been fixed. Feel free to reopen it for any question
