### ISSUE TITLE
[Feature]: Remove time travel related code 

### ISSUE THREAD

**Issue by jiaoew1991** [milvus-io/milvus-sdk-rust#65]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Since 2.3.0 Milvus deprecatd time travel feature, we should remove it in rust sdk

**Comment by aniketh-varma** [comment]
Hi @jiaoew1991, I would like to work on this issue. Can you please help me by pointing to the file which contains the code related to time travel.

**Comment by jiaoew1991** [comment]
hi @aniketh-varma you can search `travel_timestamp` in code, which should be removed

**Comment by yah01** [comment]
Hi @aniketh-varma I just checked, the time travel function has never been supported in Rust SDK, the `0` value set while querying/searching is informing the Milvus server to ignore this parameter.

We need to do nothing for this, so close it
